//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSSE680.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        /**
         * Default constructor
         * 
         */
        public Address()
        {
            this.People = new HashSet<Person>();
        }

        /**
         * String City
         * String Street
         * String State
         * int ZipCode
         */
        public Address(
                    String City,
                    String Street,
                    String State,
                    int Zipcode)
        {
            this.AddressId = AddressId;
            this.City = City;
            this.Street = Street;
            this.State = State;
            this.Zipcode = Zipcode;
        }

        /**
         * int AddressId
         * String City
         * String Street
         * String State
         * int ZipCode
         */
        public Address(
                    int AddressId,
                    String City,
                    String Street,
                    String State,
                    int Zipcode)
        {
            this.AddressId = AddressId;
            this.City = City;
            this.Street = Street;
            this.State = State;
            this.Zipcode = Zipcode;
        }


        /**
         * Setters getters for Address class
         */    
        public int AddressId { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public string State { get; set; }
        public int Zipcode { get; set; }
    
        public virtual ICollection<Person> People { get; set; }

        /**
         * Validate if the instance variables are valid
         *
         * bool - true if instance variables are valid, else false
         */
        public bool validate()
        {
            if (AddressId < 0)
            {
                return false;
            }
            if (City == null)
            {
                return false;
            }
            if (Street == null)
            {
                return false;
            }
            if (State == null)
            {
                return false;
            }
            if (Zipcode == 0)
            {
                return false;
            }

            return true;
        }    
    }
}
